DROP DATABASE IF EXISTS top_songs;
CREATE DATABASE top_songs;

use top_songs;

DROP TABLE IF EXISTS top5000;
CREATE TABLE top5000 (
position INT NOT NULL AUTO_INCREMENT,
artisti VARCHAR(100) NULL,
song VARCHAR(100) NULL,
year INT,
raw_total DECIMAL(10,4) NULL,
raw_usa DECIMAL(10,4) NULL,
raw_uk DECIMAL(10,4) NULL,
raw_eur DECIMAL(10,4) NULL,
raw_row DECIMAL(10,4) NULL,
PRIMARY KEY(position)
);

SELECT * FROM top5000